version: '3'

services:
  php:
    build: ./docker
    volumes:
      - .:/var/www:rw

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - .:/var/www:rw
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/40-custom.conf
    links:
      - php

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###